services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        volumes:
            - type: tmpfs
              target: /dev/shm
              tmpfs:
                  size: 128mb
        environment:
            POSTGRES_PASSWORD: "cu29hj8an5"
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
